### ISSUE TITLE
Version on pypi

### ISSUE THREAD

**Issue by TigorC** [coagulant/django-whatever#39]
Please you can update the version on pypi to current git:master. Last update on pypi "2012-01-22".

**Comment by log0ymxm** [comment]
+1

**Comment by GeyseR** [comment]
hey @coagulant, is it possible to give me a permission to release new versions on pypi?
Right now I have permissions to push updates to the project here on GitHub (and make this from time to time, at least for supporting newer Django versions and fixing bugs)
my pypi account is `geyser`

**Comment by GeyseR** [comment]
Done:
https://pypi.org/project/django-whatever/0.2.4/ - the last version with Django 1.1, 2.0, 2.1 and Python 2.7 support
https://pypi.org/project/django-whatever/0.3/ - the newest version with Django 3.0 support
