### ISSUE TITLE
any_field_blank should not return None if field can't be None

### ISSUE THREAD

**Issue by lampslave** [coagulant/django-whatever#49]
See [this code](https://github.com/coagulant/django-whatever/blob/18709c24f05cc5352421e10b099a62c6946ae5c3/django_any/models.py#L45-L46). I think it just lead to random errors and do nothing useful. Please let me know if you have explanation for this behavior or want me to provide pull request to fix this.

**Comment by GeyseR** [comment]
Yeah, probably there should handle two options here: for `blank` randomly return empty string and fo `null` fields - return None.
Have Pr to fix this would be awesome!
